// src/lib/magic-link.ts
//
// Passwordless onboarding entry. A magic link is generated when a client is
// created (and re-generated by the re-engagement cron if they never sign the
// contract). The link is delivered two ways:
//   1. Written to a GHL custom field (env MAGIC_LINK) + a `send-magic-link` tag
//      so a GHL workflow can fire the SMS.
//   2. Embedded in the welcome email (see src/lib/email.ts).
//
// The link logs the client straight into /onboarding via the existing
// /auth/callback PKCE exchange. The client never sees the temporary password
// the auth user was created with — they set their own during onboarding Step 3.

import { createAdminClient } from "@/lib/supabase/admin";
import { ghlUpdateContact, ghlAddTags } from "@/lib/ghl-api";

/**
 * Generates a magic (passwordless) login link that lands the client in the
 * onboarding flow. Returns the full action_link, or null if generation failed.
 */
export async function generateOnboardingMagicLink(email: string): Promise<string | null> {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";

  try {
    const supabaseAdmin = createAdminClient();
    const { data, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "magiclink",
      email: email.toLowerCase(),
      options: {
        redirectTo: `${appUrl}/auth/callback?next=/onboarding`,
      },
    });

    if (error) {
      console.error("❌ Magic link generation error:", error.message);
      return null;
    }

    return data?.properties?.action_link ?? null;
  } catch (err) {
    console.error("❌ Magic link generation threw:", err);
    return null;
  }
}

/**
 * Pushes the magic link to GHL: writes it to the MAGIC_LINK custom field and
 * adds the `send-magic-link` tag so a GHL workflow can dispatch the SMS.
 * Non-fatal — logs and swallows errors so it never breaks the calling flow.
 */
export async function pushMagicLinkToGhl(contactId: string, link: string): Promise<void> {
  const fieldId = process.env.MAGIC_LINK;
  if (!fieldId) {
    console.warn("⚠️ MAGIC_LINK env (GHL custom field id) not set — skipping GHL push");
    return;
  }

  try {
    await ghlUpdateContact(contactId, {
      customFields: [{ id: fieldId, value: link }],
    });
    await ghlAddTags(contactId, ["send-magic-link"]);
    console.log(`✅ Magic link pushed to GHL contact ${contactId} (+ send-magic-link tag)`);
  } catch (err) {
    console.error("⚠️ Failed to push magic link to GHL (non-fatal):", err);
  }
}
