// src/lib/magic-link.ts
//
// Passwordless onboarding entry. A magic link is generated when a client is
// created (and re-generated by the re-engagement cron if they never sign the
// contract). The link is delivered two ways:
//   1. Written to a GHL custom field (env MAGIC_LINK) + a `send-magic-link` tag
//      so a GHL workflow can fire the SMS.
//   2. Embedded in the welcome email (see src/lib/email.ts).
//
// The link logs the client straight into /onboarding via the existing
// /auth/callback PKCE exchange. The client never sees the temporary password
// the auth user was created with — they set their own during onboarding Step 3.

import crypto from "crypto"; // Node built-in — HMAC signing for our own long-lived tokens
import { ghlUpdateContact, ghlAddTags } from "@/lib/ghl-api";

// How long a magic link stays clickable. Supabase's own OTP tokens are capped
// at 24h (Email OTP expiry setting), which is why we DON'T embed one in the
// link anymore — clients routinely sit on the SMS/email for days. Instead the
// link carries our own HMAC-signed token (below); /auth/magic exchanges it for
// a fresh Supabase OTP at click time, so the Supabase token only has to
// survive a few milliseconds.
const MAGIC_LINK_TTL_DAYS = Number(process.env.MAGIC_LINK_TTL_DAYS || 30);

/**
 * Affiliate dashboard links are re-stamped weekly by
 * /api/cron/refresh-affiliate-links, so they get a TTL scoped to that cycle
 * rather than the 30 days a client's one-shot onboarding link needs. Short TTL
 * is the whole point: the value sits in a CRM field, so it should stop working
 * about as fast as the cron replaces it.
 *
 * 8 and not 7: the cron runs weekly at a fixed hour, and a token minted to
 * expire exactly one week later would race its own replacement — any delay in
 * the run leaves the field holding an already-dead link. The extra day is the
 * margin for one late run, not for a missed one. A MISSED run does break the
 * links until the following week; that is the accepted cost of not leaving a
 * long-lived one-click login lying around.
 */
const AFFILIATE_MAGIC_LINK_TTL_DAYS = Number(process.env.AFFILIATE_MAGIC_LINK_TTL_DAYS || 8);

function signingSecret(): string {
  const secret = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!secret) throw new Error("SUPABASE_SERVICE_ROLE_KEY missing — cannot sign magic-link tokens");
  return secret;
}

function b64url(buf: Buffer): string {
  return buf.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function hmac(payload: string): string {
  return b64url(crypto.createHmac("sha256", signingSecret()).update(payload).digest());
}

/**
 * Long-lived, stateless magic-link token: base64url(JSON{e: email, x: expiry
 * epoch-seconds}) + "." + HMAC-SHA256 signature. Stateless = no DB row and no
 * migration; verification is pure crypto in /auth/magic.
 */
export function signMagicToken(email: string, ttlDays: number = MAGIC_LINK_TTL_DAYS): string {
  const payload = b64url(Buffer.from(JSON.stringify({
    e: email.toLowerCase(),
    x: Math.floor(Date.now() / 1000) + ttlDays * 86400,
  })));
  return `${payload}.${hmac(payload)}`;
}

/** Returns the email if the token is authentic and unexpired, else null. */
export function verifyMagicToken(token: string): { email: string } | null {
  const [payload, sig] = token.split(".");
  if (!payload || !sig) return null;

  const expected = hmac(payload);
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;

  try {
    const { e, x } = JSON.parse(Buffer.from(payload.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString());
    if (typeof e !== "string" || typeof x !== "number") return null;
    if (Math.floor(Date.now() / 1000) > x) return null;
    return { email: e };
  } catch {
    return null;
  }
}

/**
 * Generates a magic (passwordless) login link that lands the client in the
 * onboarding flow. Returns a link to OUR /auth/magic route, or null if
 * generation failed.
 *
 * History: this used to embed Supabase's `hashed_token` (pointing at
 * /auth/confirm), but those tokens expire with the project's Email OTP setting
 * — 1h by default, 24h hard max — and clients often click days later. Now the
 * link carries our own MAGIC_LINK_TTL_DAYS-day signed token; /auth/magic mints
 * and verifies a fresh Supabase OTP server-side at click time. The domain
 * comes from NEXT_PUBLIC_APP_URL, so it honors localhost in dev with no
 * Supabase config. (We still deliberately avoid Supabase's `action_link`: its
 * redirect_to must be whitelisted and it lands tokens in a #hash outside our
 * PKCE /auth/callback.)
 */
export async function generateOnboardingMagicLink(email: string): Promise<string | null> {
  try {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";
    const token = signMagicToken(email);
    const next = encodeURIComponent("/onboarding");
    return `${appUrl}/auth/magic?token=${token}&next=${next}`;
  } catch (err) {
    console.error("❌ Magic link generation threw:", err);
    return null;
  }
}

/**
 * Same passwordless login as generateOnboardingMagicLink, but lands the client
 * on their /dashboard instead of /onboarding. Used by the Speed Form doc-release
 * flow (src/lib/speed-form.ts): by the time documents are released the client
 * has already finished onboarding + signed, so the doc-request email should drop
 * them straight on the dashboard where the document checklist lives.
 */
export async function generateDocUploadMagicLink(email: string): Promise<string | null> {
  try {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";
    const token = signMagicToken(email);
    const next = encodeURIComponent("/dashboard");
    return `${appUrl}/auth/magic?token=${token}&next=${next}`;
  } catch (err) {
    console.error("❌ Doc-upload magic link generation threw:", err);
    return null;
  }
}

/**
 * Same passwordless login, for the Level-2 referral-partner portal.
 *
 * Lands on /partner/welcome, which asks them to choose a password and then
 * forwards to the dashboard. It forwards straight through on later clicks, so
 * the same link works as both the invite and a re-send.
 *
 * Partners are invited professionals (CPAs, bankers) — mailing them a temporary
 * password to type in is both worse security and a worse first impression than
 * a link that just works. The auth user is created with a random password nobody
 * ever sees, so this link is the ONLY way in until they set one.
 * See [[magic_link_onboarding]].
 */
export async function generatePartnerPortalMagicLink(email: string): Promise<string | null> {
  try {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";
    const token = signMagicToken(email);
    const next = encodeURIComponent("/partner/welcome");
    return `${appUrl}/auth/magic?token=${token}&next=${next}`;
  } catch (err) {
    console.error("❌ Partner portal magic link generation threw:", err);
    return null;
  }
}

/**
 * Same passwordless login, landing an affiliate on /affiliate/dashboard.
 *
 * Written to the "[Data Vault] Affiliate Dashboard Link" custom field so GHL
 * reminder and re-activation emails merge a one-click entry instead of a login
 * form. It carries a deliberately SHORT TTL (AFFILIATE_MAGIC_LINK_TTL_DAYS, one
 * week + a day) and is kept usable by /api/cron/refresh-affiliate-links
 * re-stamping it weekly, rather than by handing out a long-lived credential.
 * GHL merges the field at SEND time, so a weekly-fresh field is all a
 * months-later campaign needs; a link in an already-delivered email going stale
 * is fine, and is the point.
 *
 * Affiliates DO set a password at signup, so this is convenience rather than
 * the only way in (which is what it is for clients and partners).
 */
export async function generateAffiliateDashboardMagicLink(email: string): Promise<string | null> {
  try {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";
    const token = signMagicToken(email, AFFILIATE_MAGIC_LINK_TTL_DAYS);
    const next = encodeURIComponent("/affiliate/dashboard");
    return `${appUrl}/auth/magic?token=${token}&next=${next}`;
  } catch (err) {
    console.error("❌ Affiliate dashboard magic link generation threw:", err);
    return null;
  }
}

/**
 * Pushes the magic link to GHL: writes it to the MAGIC_LINK custom field and
 * adds the `send-magic-link` tag so a GHL workflow can dispatch the SMS.
 * Non-fatal — logs and swallows errors so it never breaks the calling flow.
 */
export async function pushMagicLinkToGhl(contactId: string, link: string): Promise<void> {
  const fieldId = process.env.MAGIC_LINK;
  if (!fieldId) {
    console.warn("⚠️ MAGIC_LINK env (GHL custom field id) not set — skipping GHL push");
    return;
  }

  try {
    await ghlUpdateContact(contactId, {
      customFields: [{ id: fieldId, value: link }],
    });
    await ghlAddTags(contactId, ["send-magic-link"]);
    console.log(`✅ Magic link pushed to GHL contact ${contactId} (+ send-magic-link tag)`);
  } catch (err) {
    console.error("⚠️ Failed to push magic link to GHL (non-fatal):", err);
  }
}
