"use client";

import { cn } from "@/lib/utils";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function AdvisorSignUpForm({
  className,
  ...props
}: React.ComponentPropsWithoutRef<"div">) {
  // Form state management
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [profilePic, setProfilePic] = useState<File | null>(null);
  const [password, setPassword] = useState("");
  const [repeatPassword, setRepeatPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const router = useRouter();

  /**
   * Handles the advisor signup process
   * - Creates auth user via Supabase
   * - Uploads profile picture to Supabase Storage
   * - Assigns 'advisor' role in public.users table
   * - Creates entry in public.advisors table
   * - Creates contact in GHL with advisor tag
   */
  const handleAdvisorSignUp = async (e: React.FormEvent) => {
    e.preventDefault();
    const supabase = createClient();

    setIsLoading(true);
    setError(null);

    // Validation: Check if passwords match
    if (password !== repeatPassword) {
      setError("Passwords do not match");
      setIsLoading(false);
      return;
    }

    // Validation: Ensure first name is provided
    if (!firstName.trim()) {
      setError("Please provide first name");
      setIsLoading(false);
      return;
    }

    // Validation: Check password strength (minimum 6 characters)
    if (password.length < 6) {
      setError("Password must be at least 6 characters");
      setIsLoading(false);
      return;
    }

    try {
      // Step 1: Prepare profile picture (convert to base64 for server-side upload)
      let profilePicBase64: string | null = null;
      let profilePicName: string | null = null;

      if (profilePic) {
        profilePicName = profilePic.name;
        // Convert file to base64
        profilePicBase64 = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.readAsDataURL(profilePic);
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = (error) => reject(error);
        });
      }

      // Step 2: Normalize last name (set to null if empty)
      const normalizedLastName = lastName.trim() === "" ? null : lastName.trim();

      // Step 3: Call API to create user record with 'advisor' role and GHL contact
      // This API now handles the entire signup process including auth user creation
      const res = await fetch("/api/post-signup-advisor", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          // userId is no longer needed, generated by API
          firstName: firstName.trim(),
          lastName: normalizedLastName,
          email: email.trim().toLowerCase(),
          phone: phone.trim() || null,
          profilePicBase64, // Send base64 image
          profilePicName,   // Send filename
          password, // Include password for welcome email AND auth creation
          // Add advisor-specific tags for GHL
          tags: ["creditbanc-advisor", "advisor-signup"],
        }),
      });

      if (!res.ok) {
        const { message } = await res.json().catch(() => ({
          message: "Server error"
        }));
        throw new Error(message || "Failed advisor signup flow");
      }

      // Step 6: Redirect to success page
      router.push("/auth/advisor-signup-success");
    } catch (err: any) {
      setError(err?.message || "An error occurred during signup");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">Advisor Sign Up</CardTitle>
          <CardDescription>
            Create your advisor account to start managing client applications
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleAdvisorSignUp}>
            <div className="flex flex-col gap-6">
              {/* First Name Input */}
              <div className="grid gap-2">
                <Label htmlFor="first-name">First Name</Label>
                <Input
                  id="first-name"
                  type="text"
                  placeholder="John"
                  required
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                />
              </div>

              {/* Last Name Input */}
              <div className="grid gap-2">
                <Label htmlFor="last-name">Last Name</Label>
                <Input
                  id="last-name"
                  type="text"
                  placeholder="Doe"
                  required
                  value={lastName}
                  onChange={(e) => setLastName(e.target.value)}
                />
              </div>

              {/* Email Input */}
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="advisor@creditbanc.com"
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>

              {/* Phone Input */}
              <div className="grid gap-2">
                <Label htmlFor="phone">Phone (Optional)</Label>
                <Input
                  id="phone"
                  type="tel"
                  placeholder="+1 (555) 123-4567"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                />
              </div>

              {/* Profile Picture Input */}
              <div className="grid gap-2">
                <Label htmlFor="profile-pic">Profile Picture (Optional)</Label>
                <Input
                  id="profile-pic"
                  type="file"
                  accept="image/*"
                  onChange={(e) => setProfilePic(e.target.files?.[0] || null)}
                />
                {profilePic && (
                  <p className="text-sm text-muted-foreground">
                    Selected: {profilePic.name}
                  </p>
                )}
              </div>

              {/* Password Input */}
              <div className="grid gap-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="••••••••"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>

              {/* Repeat Password Input */}
              <div className="grid gap-2">
                <Label htmlFor="repeat-password">Confirm Password</Label>
                <Input
                  id="repeat-password"
                  type="password"
                  placeholder="••••••••"
                  required
                  value={repeatPassword}
                  onChange={(e) => setRepeatPassword(e.target.value)}
                />
              </div>

              {/* Error Message Display */}
              {error && (
                <p className="text-sm text-red-500 font-medium">{error}</p>
              )}

              {/* Submit Button */}
              <Button
                type="submit"
                className="w-full"
                disabled={isLoading}
              >
                {isLoading ? "Creating advisor account..." : "Create Advisor Account"}
              </Button>
            </div>

            {/* Login Link */}
            <div className="mt-4 text-center text-sm">
              Already have an account?{" "}
              <Link
                href="/auth/login"
                className="underline underline-offset-4 hover:text-primary"
              >
                Login
              </Link>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
