/**
 * SEED + FALLBACK ONLY — no longer the live source of the dropdown.
 *
 * The internal referral-partner list now lives in the `referral_partners` table
 * (migration 20260718) and is managed at /admin/referral-partners or inline from
 * the client card. Admins add new partners there — do NOT edit this file to add a
 * partner; it won't show up unless the DB row is also created.
 *
 * This array is used only to:
 *   1. seed the table on first migration apply, and
 *   2. serve as a last-resort fallback in getActiveReferralPartners() when the
 *      table can't be read (see src/lib/referral-partners.ts).
 *
 * The selected name is persisted to client_data_vault.referral_partner (plus the
 * referral_partner_id FK) and synced to the GHL field "Referral Assigned"
 * ({{contact.data_vault_referral_assigned}}). Keep alphabetized.
 *
 * NOTE: as of migration 20260807 a partner is more than a name — they carry a
 * link slug, portal access and commission terms. None of that can live here, so
 * this list is now strictly the emergency fallback for the dropdown.
 *
 * This file HAS DRIFTED from production before, and the drift is expensive: it
 * seeded "Chris Scheneider" into the migration while prod already held the
 * correct "Chris Schneider", which inserted a duplicate person rather than
 * failing. Two names below are still misspelled relative to the links in
 * circulation ("Nathasha Atto", "Tersea Wagonseller") — those match prod, and
 * the migration maps the right slug onto them rather than renaming, because the
 * name is what already-attributed clients carry. Fix them at
 * /admin/referral-partners (which updates both the registry and every client).
 */
export const REFERRAL_PARTNERS: readonly string[] = [
    "Aaron Sedlacek",
    "ACG",
    "Albert Anderson",
    "Alberto Tovela",
    "Alexis Sadler",
    "Ali Ghamlouch",
    "Anabel Lopez",
    "Angela Golden",
    "Anisa Braka",
    "August Biniaz",
    "Bill Hand",
    "Byron Hough",
    "Byron Logan",
    "Cassie Rigg",
    "Cesar Silva",  
    "Chad Brown",
    "Chad Harward",
    "Charina Padilla",
    "Daniel Ortega",
    "David Fretz",
    "Dawn Brady",
    "Deirdre Venturella",
    "DM",
    "Dorothy Buford",
    "Dylan Viskochil",
    "Erick Parker",
    "Ethel Shaffer",
    "Felicia Barras",
    "Gathering the Kings Network",
    "Hank Honas",
    "Hardik Shah",
    "Heather Bowers",
    "Henry Duran",
    "Humberto Robles",
    "Ivan Feliciano",
    "James Alexander",
    "Janel Sykora",
    "Jason Armstrong",
    "Javier Silva",
    "Jeff Holman",
    "Jeffrey Villwock",
    "Jennifer Krause",
    "John Crisafulli",
    "John Eastwood",
    "John Luke",
    "Julio Gonzalez",
    "Keira Brings",
    "Kimberly Baker",
    "King McCray",
    "Kunal Mansukhani",
    "Layla Martinez",
    "Lawrence Aguero",
    "Linkedin",
    "Lubna Rana",
    "Luke Scott",
    "Magda Lissette Crnkovich",
    "Marci McAdoo",
    "Mardochee Louis",
    "Mario Davis",
    "Matt Hehl",
    "Michael McCormick",
    "Michael Spino",
    "Michael Walsh",
    "Miguel Hernandez",
    "Mohammed Hussain",
    "Mohd Salahuddin",
    "Morgan Anderson",
    "Morgan Miller",
    "Nand Gangwani",
    "Nathan Caldwell",
    "Nathasha Atto",
    "Nguyen Tran",
    "Nicole E. Kimes",
    "Peter Bellina",
    "Richard C. Wilson",
    "Richard Freiberg",
    "Richard Rodriguez",
    "Rodney W. Deloe",
    "Rodrigo Barbonetti",
    "Ron Abraham",
    "Sean Shanks",
    "Sherry Winczewski",
    "Steven Bellafiore",
    "Tammy Cook",
    "Tanya Akimenko",
    "Tersea Wagonseller",
    "Thomas Huston",
    "Timothy Schwan",
    "Tom Ferry",
    "Vanessa Aviles",
    "Victor Nocera",
    "Vincent M Sirianni",
    "Vivian Gant",
    "Weston Holley",
    "Zahra Yarahamdi",
    "Chris Schneider",
    "Santo Chiarelli",

];
